sudo: false
dist: trusty

env:
  global:
    - GH_USER_EMAIL="cookbooks@schubergphilis.com"
    - GH_USER_NAME="SBP Cookbooks CI"
    - GH_REPO="sbp-cookbooks/terraform-github-org"
    - secure: "iH+aXQN/obeW05IBlG7VePYJcs6Q56lPBkf+EUbXxl/vXteFlIevBUXf1F7LK93+BAcyc3A0aEMeKXrCW3WWIgaaHiMly5SJ00eWYwQ22fQpG+ONcGlgGZaEZ1i/D82xDLxQWEN0w8G8liV615JpPsQ4oYZMZglI+J3QJUyU9f6YN2WkeUCFr19kFpeBpt8Q3sZLOxclZ7Wqaa+SlldTQR7wx0pAmZCYlHfqwTmIwo4AJf3mmZ/5BNAguBtqklIzSOVxEs1aZB78Y3KcoE8L0RROm/fvAEOqRskezJKJpWm34UNFdG8leXe048T7LZu8oDe6aMcREvGEVio3Y5Q1cBiihs/VnYUaaXtni/JhZpgnEv+z7Hvyh+xzaiuYCELUFwkSGOTel7TgLucLGVRw6Pq9HosLQvSCE23mLjnN8NWaA0KBbfNLlGvnV3j78eKYx9HmvoPUZ8k+wBQb12Vlaiq3VbDEv7WHUwy5fbmd3PYOqLHfe6avcQiL6nGw6NG+lavAe8yLad9zltysZ7XOwP23ZsU/8d8ij7q+SOV4Pg9iVkyDGCxmaKjuFVFi2M5t1toqZ2MfJYh8+UdKbgsig/QZ06vzE06oMwcVyuNoeN+QDqwRxBJx1NrlgpoJu+lk//oRTqdvX/gWJuQqje7zT4spHfITiGK3kOh6/YlztNg="

install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.9.3/terraform_0.9.3_linux_amd64.zip" -o /tmp/terraform.zip
  - unzip /tmp/terraform.zip -d /opt/terraform
  - export PATH=/opt/terraform:$PATH

script:
  - ./plan_builder.rb
  - terraform plan

deploy:
  - provider: script
    skip_cleanup: true
    script: "./deploy.sh"
    on:
      repo: sbp-cookbooks/terraform-github-org
      branch: master
      condition: "$(git diff @~1 --name-only | grep .tf$)"
