repos:
    - name: sbp_emet
      description: Microsoft EMET
    - name: sbp_mcafee
      description: McAfee
    - name: sbp_messageanalyzer
      description: Message Analyzer
    - name: mercury
      description: Mercury Global Loadbalancer

users:
    - name: shoekstra
      repos: all
    - name: rdoorn
      repos: mercury
